spring:
  application:
    name: tste-dsin
  datasource:
    driver-class-name: driver-do-seu-banco-relacional
    url: jdbc:mysql://localhost:3306/seu-banco
    username: seu-usuario
    password: sua-senha
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false

security:
  jwt:
    secretKey: sua-secret-key (pode ser qualquer String)
    expirationInMillisecond: 1800000